Finish Session-04/task-1
NicatBabayev/mastering-golang-tasks pull request #4
Opened 2024-10-01 13:07 UTC by NicatBabayev

2024-10-01 18:17 UTC, zaur-adigozalov requested changes
It works, you did some extra which gives positive points. But still code is not clean, and it's hard to read for other developers

I uploaded the homework task which I'd like to do as homework - https://github.com/zaur-adigozalov/mastering-golang-sessions/blob/main/sessions/4/HOMEWORK.go

You can check it and find some tricks based on homework requirements

2024-10-01 18:17 UTC, zaur-adigozalov commented on session-4/TaskManagementSystem/main.go
> +}
TasksAvailable is a const and you can create a function to calculate tasks remaining and whether the project is near completion (multiple return values) in the same function
```suggestion
func calculateTasksRemaining(tasksCompleted int) (int, bool) {
    tasksRemaining := tasksAvailable - tasksCompleted
    nearCompletion := tasksCompleted > 90
    return tasksRemaining, nearCompletion
}
```

2024-10-01 18:17 UTC, zaur-adigozalov commented on session-4/TaskManagementSystem/main.go
> +}
You can remove this method, merging with calculateTasksRemaining

2024-10-01 18:17 UTC, zaur-adigozalov commented on session-4/TaskManagementSystem/main.go
> +}
It's good to use map, even any type, but we can still use string slices (we used it before in our samples)
```suggestion

    tasks := []string{"Task 1", "Task 2", "Task 3", "Task 4", "Task 5"}
    printTasks(tasks...)
    
    // Variadic function to print any number of tasks
func printTasks(tasks ...string) {
    fmt.Println("Task list:")
    for i, task := range tasks {
        fmt.Printf("%d: %s\n", i+1, task)
    }
}
```

2024-10-01 18:17 UTC, zaur-adigozalov commented on session-4/TaskManagementSystem/main.go
> +		printTaskDetails(m)
No need to use map for this case, but I like your approach

2024-10-01 18:17 UTC, zaur-adigozalov commented on session-4/TaskManagementSystem/main.go
> +	if tasksRemaining(tasksCompleted) >= 0 {
Still you can use suggested "calculateTasksRemaining" with multiple values

2024-10-02 05:23 UTC, NicatBabayev commented
Thank you for the comments. I see that I have to practice on clean code principles. Is there any resource you can suggest to learn the basics of clean code? Or some repos with neatly written go code?

2024-10-02 05:25 UTC, NicatBabayev commented
I do not want just blindly commit your suggestions. So this PR will be open until I fully understand how refactor my code correctly. If you see that I am missing session-04 in my `main` branch please ignore.

2024-10-06 16:16 UTC, merged